# 프로그래머스 # 가격이 제일 비싼 식품의 정보 출력하기

# 풀이 1: MAX 활용
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

# 풀이 2: DESC 정렬 후 LIMIT 사용

SELECT *
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1
