# 프로그래머스 # 그룹별 조건에 맞는 식당 목록 출력하기
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN (SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE FROM REST_REVIEW 
      WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID HAVING COUNT(*) = (SELECT MAX(CNT) FROM (SELECT COUNT(*) AS CNT FROM REST_REVIEW GROUP BY MEMBER_ID) A))) RR
ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY REVIEW_DATE