# 프로그래머스 # 서울에 위치한 식당 목록 출력하기 # lv 4
-- 첫번째 풀이 
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO
JOIN REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE LEFT(ADDRESS,2) LIKE '서울%'
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

-- 두번째 풀이
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO
INNER JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID) AS REST_AVG_REVIEW
ON REST_INFO.REST_ID = REST_AVG_REVIEW.REST_ID
WHERE LEFT(ADDRESS,2) LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC
