# 프로그래머스 # 성분으로 구분한 아이스크림 총 주문량

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f
JOIN ICECREAM_INFO i
WHERE f.FLAVOR = i.FLAVOR # USING (FLAVOR) 도 가능
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER