# 프로그래머스 # 자동차 평균 대여 기간 구하기

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) + 1 AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

# DATEDIFF : 두 날짜의 차이를 일수로 반환
# AVERAGE : 평균을 반환
# ROUND(대상, 자릿수) : 대상을 자릿수까지 반올림